version: '3.9'

services:

  app:
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
    ports:
       - 8020:8000
    networks:
      - app_network
    environment:
      - APP_NAME
      - APP_VERSION
      - APP_UID
      - APP_GID
      - APP_VIRTUAL_HOSTNAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
    depends_on:
      - postgres
    entrypoint: [ "/home/app/docker-entrypoint.dev.sh" ]
    command: python /home/app/appsite/manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-postgres
    volumes:
      - postgres_db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app_network
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

volumes:
  postgres_db_volume:

networks:
  app_network:
    external:
      name: ${APP_NAME}-backend


