#!/bin/bash
set -e

echo "------ build ------"

./init
source .env
cp .env context/build

docker-compose -f context/build/docker-compose.build.yml build base cactvs
docker-compose -f context/build/docker-compose.build.yml build cactvs-conda
docker-compose -f context/build/docker-compose.build.yml build cactvs-django-app-server
