#!/bin/bash
set -e

echo "------ build ------"

./init
source .env
cp .env context/build

#cp -r ./context/pycactvs-djangp-app-server/nginx ./context/build/cactvs-django-app-server

#./env-prepare

docker-compose -f context/build/docker-compose.build.yml build base cactvs
docker-compose -f context/build/docker-compose.build.yml build cactvs-conda
docker-compose -f context/build/docker-compose.build.yml build cactvs-django-app-server
