#!/bin/bash
set -e

echo "------ init base ------"

source settings.env
cp settings.env .env

####./env-prepare

#source settings.env

echo "1 >>> $CACTVS_HOME"

cp app.template.env app.env
./context/share/env-parse
cp app.env .env
#rm app.env

#echo "ENV PREPARE"

#cp app.env context/build/

source .env

echo "2 ... $CACTVS_HOME"


#######


source .env

echo "0 >>> $CACTVS_HOME"

CWD=$(pwd)

mkdir -p $CACTVS_HOME

echo "init pycactvs at ${CACTVS_HOME}"
cp -r ./context/app/pycactvs $CACTVS_HOME
cp -r ./context/share/* $CACTVS_HOME/pycactvs
cd $CACTVS_HOME/pycactvs
cp $CWD/.env .
sed -i -e 's?@CACTVS_HOME?'${CACTVS_HOME}/pycactvs'?g' app.template.env
sed -i -e 's?@APP_HOME?'${APP_HOME}'?g' app.template.env
./init
cd $CWD

echo "BLAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1"


echo "init pycactvs-conda at ${CACTVS_HOME}"
cp -r ./context/app/pycactvs-conda $CACTVS_HOME
cp -r ./context/share/* $CACTVS_HOME/pycactvs-conda
cd $CACTVS_HOME/pycactvs-conda
cp $CWD/.env .
sed -i -e 's?@CACTVS_HOME?'${CACTVS_HOME}/pycactvs-conda'?g' app.template.env
sed -i -e 's?@APP_HOME?'${APP_HOME}'?g' app.template.env
./init
cd $CWD

echo "BLAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2"

#echo "Init app at ${APP_HOME}"
#cp -r ./context/app/pycactvs-django-nginx $APP_HOME
#cp -r ./context/share/* $APP_HOME
#cd $APP_HOME
#./init
#cd $CWD