version: '3.9'

services:

  cspy:
    image: docker-cactvs-conda:${CACTVS_VERSION}
    container_name: ${CACTVS_VERSION}
    volumes:
      - ${CACTVS_HOME}:/home/app
    environment:
      - CACTVS_HOME
      - CACTVS_UID
      - CACTVS_GID
    entrypoint: [ "/home/app/docker-entrypoint.sh" ]
    #command: ["/opt/cactvs/bin/cspy"]
    working_dir: "/home/app"


